version: 2.1

orbs:
  codecov: codecov/codecov@5.4.3

jobs:
  test:
    docker:
      - image: circleci/clojure:tools-deps
    environment:
      JAVA_TOOL_OPTIONS: -Xmx3200m
    steps:
      - checkout
      - run: clojure -Atest --skip-meta :slow --plugin cloverage --codecov
      - codecov/upload:
          file: target/coverage/codecov.json

workflows:
  workflow:
    jobs:
      - test
